# Generated by Django 4.2.4 on 2023-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_doktora', models.CharField(max_length=30)),
                ('prezime_doktora', models.CharField(max_length=30)),
                ('opis_doktora', models.TextField()),
                ('email_doktora', models.EmailField(max_length=254)),
                ('iskustvo_doktora', models.TextField()),
                ('specijalizacija_doktora', models.CharField(choices=[('AN', 'Anesteziolog'), ('IN', 'Infektolog'), ('KA', 'Kardiolog'), ('PE', 'Pedijatar'), ('RE', 'Reumatolog'), ('PU', 'Pulmolog'), ('UR', 'Urolog'), ('ON', 'Onkolog')], max_length=2)),
            ],
        ),
    ]
