# Generated by Django 4.2.4 on 2023-08-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='specijalizacija_doktora',
            field=models.CharField(choices=[('AN', 'Anesteziolog'), ('IN', 'Infektolog'), ('KA', 'Kardiolog'), ('PE', 'Pedijatar'), ('RE', 'Reumatolog'), ('PU', 'Pulmolog'), ('UR', 'Urolog'), ('ON', 'Onkolog')], default='AN', max_length=2),
        ),
    ]
