# Generated by Django 4.1.7 on 2023-09-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0003_narudzba'),
    ]

    operations = [
        migrations.AddField(
            model_name='narudzba',
            name='vrijeme_pregelda',
            field=models.TimeField(default='08:00'),
        ),
    ]
