# Generated by Django 4.1.7 on 2023-09-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0005_alter_narudzba_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narudzba',
            name='vrijeme_pregelda',
        ),
        migrations.AddField(
            model_name='narudzba',
            name='prezime_pacijenta',
            field=models.CharField(default='Peric', max_length=120),
        ),
    ]
