# Generated by Django 4.1.7 on 2023-09-03 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0008_narudzba'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
