# Generated by Django 4.1.7 on 2023-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0009_doktor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
