# Generated by Django 4.1.7 on 2023-09-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0010_alter_doktor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='slika_doktora',
            field=models.ImageField(default='default.jpg', upload_to='profilne_slike'),
        ),
        migrations.DeleteModel(
            name='Narudzba',
        ),
    ]
