# Generated by Django 4.1.7 on 2023-09-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0012_narudzba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktor',
            name='slika_doktora',
        ),
    ]
