# Generated by Django 4.1.7 on 2023-09-06 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0013_remove_doktor_slika_doktora'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomZdravlja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_doma_zdravlja', models.CharField(max_length=40)),
                ('adresa_doma_zdravlja', models.CharField(max_length=30)),
                ('opis_doma_zdravlja', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicinskaSestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_sestre', models.CharField(max_length=30)),
                ('prezime_sestre', models.CharField(max_length=30)),
                ('godine_staza_sestre', models.IntegerField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
