# Generated by Django 4.1.7 on 2023-09-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0014_domzdravlja_medicinskasestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='dom_zdravlja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zdravstveni_sustav_app.domzdravlja'),
        ),
    ]
