# Generated by Django 4.1.7 on 2023-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0015_doktor_dom_zdravlja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='specijalizacija_doktora',
            field=models.CharField(choices=[('Anesteziolog', 'Anesteziolog'), ('Infektolog', 'Infektolog'), ('Kardiolog', 'Kardiolog'), ('Pedijatar', 'Pedijatar'), ('Reumatolog', 'Reumatolog'), ('Pulmolog', 'Pulmolog'), ('Urolog', 'Urolog'), ('Onkolog', 'Onkolog')], default='AN', max_length=30),
        ),
    ]
