# Generated by Django 4.1.7 on 2023-09-09 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zdravstveni_sustav_app', '0016_alter_doktor_specijalizacija_doktora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktor',
            name='dom_zdravlja',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zdravstveni_sustav_app.domzdravlja'),
        ),
        migrations.AlterField(
            model_name='medicinskasestra',
            name='doktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
